src/java/domain/Depoimento.java
package domain;

public class Depoimento
{
    private static int LAST_ID = 0;

    String name;
    String email;
    String comment;
    int id;

    public Depoimento(String name, String email, String comment)
    {
        this.name = name;
        this.email = email;
        this.comment = comment;
        this.id = LAST_ID++;
    }

    public String getName()
    {
        return name;
    }

    public String getEmail()
    {
        return email;
    }

    public String getComment()
    {
        return comment;
    }

    public Integer getId()
    {
        return id;
    }
}

src/java/domain/Usuario.java
package domain;

public class Usuario
{
    String username;
    String password;

    public Usuario(String username, String password)
    {
        this.username = username;
        this.password = password;
    }

    public String getUsername()
    {
        return username;
    }

    public String getDisplayName()
    {
        return username.substring(0, 1).toUpperCase() + username.substring(1);
    }

    public String getPassword()
    {
        return password;
    }

    public boolean getIsAdmin()
    {
        return "admin".equals(username);
    }
}

src/java/control/DepoimentoController.java
package control;

import domain.Depoimento;
import domain.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.*;
import javax.servlet.*;

public class DepoimentoController
{
    HttpServletRequest request;
    HttpServletResponse response;
    ServletContext context;

    public DepoimentoController(HttpServletRequest request, HttpServletResponse response, ServletContext context)
    {
        this.request = request;
        this.response = response;
        this.context = context;
    }

    private List<Depoimento> getDepoimentos()
    {
        List<Depoimento> depoimentos = (List<Depoimento>) request.getSession().getAttribute("depoimentos");
        if(depoimentos == null) {
            depoimentos = new ArrayList<>();
        }
        return depoimentos;
    }

    public void list(String contextPath) throws Exception
    {
        request.setAttribute("depoimentos", getDepoimentos());
        request.setAttribute("error", request.getSession().getAttribute("error"));
        request.getSession().removeAttribute("error");
        RequestDispatcher dsp = request.getRequestDispatcher("/views/depoimento.jsp");
        dsp.forward(request, response);
    }

    public void submit(String contextPath) throws Exception
    {
        String name = request.getParameter("name");
        String email = request.getParameter("email");
        String comment = request.getParameter("comment");
        if(name != null && email != null && comment != null && !name.isEmpty() && email.matches(".+@.+\\..+")) {
            List<Depoimento> depoimentos = getDepoimentos();
            depoimentos.add(new Depoimento(name, email, comment));
            request.getSession().setAttribute("depoimentos", depoimentos);
        }
        else {
            request.getSession().setAttribute("error", "Os dados inseridos são inválidos, tente novamente");
        }
        response.sendRedirect(contextPath + "/depoimento/list");
    }

    public void delete(String contextPath) throws Exception
    {
        Usuario user = (Usuario) request.getSession().getAttribute("user");
        if(user != null && user.getIsAdmin()) {
            try {
                Integer id = Integer.parseInt(request.getParameter("id"));
                List<Depoimento> depoimentos = getDepoimentos();
                for(Depoimento dep : depoimentos) {
                    if(dep.getId().equals(id)) {
                        depoimentos.remove(dep);
                        break;
                    }
                }
                request.getSession().setAttribute("depoimentos", depoimentos);
            }
            catch(NumberFormatException ex) {
                request.getSession().setAttribute("error", "Depoimento inválido");
            }
        }
        else {
            request.getSession().setAttribute("error", "Você não tem permissão para fazer esta ação");
        }
        response.sendRedirect(contextPath + "/depoimento/list");
    }
}

src/java/control/FrontController.java
package control;

import java.io.IOException;
import java.lang.reflect.*;
import javax.servlet.annotation.*;
import javax.servlet.http.*;
import javax.servlet.*;

@WebServlet(name = "FrontController",
        urlPatterns = {"/app/*"},
        initParams = {
            @WebInitParam(name = "usuario", value = "control.UsuarioController"),
            @WebInitParam(name = "depoimento", value = "control.DepoimentoController")
        }
)

public class FrontController extends HttpServlet
{

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");

        String contextPath = getServletContext().getContextPath() + "/app";
        request.setAttribute("resources", getServletContext().getContextPath());
        request.setAttribute("context", contextPath);

        String path = request.getRequestURI();
        int pos1 = path.lastIndexOf("/");
        int pos2 = path.lastIndexOf("/", pos1 - 1);
        String action = path.substring(pos1 + 1, path.length());
        String module = path.substring(pos2 + 1, pos1);

        String className = getInitParameter(module);
        try {
            Class<Object> controllerClass = (Class<Object>) Class.forName(className);
            Constructor<Object> constructor = controllerClass.getConstructor(HttpServletRequest.class, HttpServletResponse.class, ServletContext.class);
            Object controller = constructor.newInstance(request, response, getServletContext());
            Class[] parameters = {String.class};
            Method method = controller.getClass().getDeclaredMethod(action, parameters);
            method.invoke(controller, contextPath);
        }
        catch(InvocationTargetException error) {
            response.setHeader("Content-Type", "text/plain");
            error.getCause().printStackTrace(response.getWriter());
        }
        catch(Exception error) {
            response.setHeader("Content-Type", "text/plain");
            error.printStackTrace(response.getWriter());
        }
    }

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
        processRequest(request, response);
    }
}

src/java/control/UsuarioController.java
package control;

import domain.Usuario;
import javax.servlet.http.*;
import javax.servlet.*;

public class UsuarioController
{
    HttpServletRequest request;
    HttpServletResponse response;
    ServletContext context;

    public UsuarioController(HttpServletRequest request, HttpServletResponse response, ServletContext context)
    {
        this.request = request;
        this.response = response;
        this.context = context;
    }

    public void login(String contextPath) throws Exception
    {
        String username = request.getParameter("username");
        String password = request.getParameter("password");
        if(username != null && password != null && username.equals("admin") && password.equals("123456")) {
            Usuario user = new Usuario(username, password);
            request.getSession().setAttribute("user", user);
        }
        else {
            request.getSession().setAttribute("error", "Login inválido!");
        }
        response.sendRedirect(contextPath + "/depoimento/list");
    }

    public void logout(String contextPath) throws Exception
    {
        request.getSession().setAttribute("user", null);
        response.sendRedirect(contextPath + "/depoimento/list");
    }
}

web/views/depoimento.jsp
<%-- 
    Document   : depoimento
    Created on : May 4, 2016, 3:33:30 PM
    Author     : Ricardo Maes
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="${resources}/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="${resources}/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css" href="${resources}/css/estilo.css"/>
        <title>Ricardo Maes Zaguini Nunes</title>
        <style>
            body {
                background-image: url(${resources}/img/bricks.jpg);
                background-repeat: repeat;
            }
        </style>
    </head>
    <body>
        <jsp:include page="header.jsp">
            <jsp:param name="selected" value="btn-contato"/>
        </jsp:include>
        <div class="container content">
            <ol class="breadcrumb">
                <li><a href="#">Meu Site</a></li>
                <li class="active">Depoimentos</li>
            </ol>
            <c:if test="${error != null}">
            <div class="alert alert-danger fade in">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <span><c:out value="${error.toString()}"/></span>
            </div>
            </c:if>
            <div class="page-header">
                <h1>Depoimentos</h1>
            </div>
            <div id="depoimentos">
                <c:if test="${depoimentos.isEmpty()}">
                    <h2 class="text-muted">Nenhum depoimento ainda...</h2><br><br>
                </c:if>
                <c:forEach items="${depoimentos}" var="dep">
                    <blockquote>
                        <div class="row">
                            <div class="col-md-11 col-xs-10">
                                <h2 class="text-capitalize"><c:out value="${dep.name}:"/></h2>
                            </div>
                            <div class="col-md-1 col-xs-2">
                                <img class="gravatar img-circle img-responsive" title="<c:out value="${dep.email}"/>">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-muted"><c:out value="${dep.comment}"/></p>
                                <c:if test="${user.isAdmin}">
                                <a class="pull-right" href="${context}/depoimento/delete?id=${dep.id}" title="Remover este depoimento"><span class="glyphicon glyphicon-remove text-danger"></span></a>
                                </c:if>
                            </div>
                        </div>
                    </blockquote>
                </c:forEach>
            </div>
            <h2>Deixe o seu:</h2>
            <form id="comment_form" method="post" action="${context}/depoimento/submit">
                <div class="input-group">
                    <label for="input-name" class="input-group-addon">Nome:</label>
                    <input type="text" id="input-name" name="name" class="form-control" placeholder="Foo Bar da Silva">
                    <label id="name_feedback" for="input-name" class="input-group-addon" data-toggle="tooltip" data-placement="left" title="O nome não pode ser vazio">
                        <span class="glyphicon glyphicon-alert icon-color-warning"></span>
                    </label>
                </div>
                <div class="input-group">
                    <label for="input-email" class="input-group-addon">E-mail:</label>
                    <input type="email" id="input-email" name="email" class="form-control" placeholder="foobar@exemplo.com">
                    <label for="input-email" id="email_feedback" class="input-group-addon" data-toggle="tooltip" data-placement="left" title="O endereço de E-mail é inválido">
                        <span class="glyphicon glyphicon-alert icon-color-warning"></span>
                    </label>
                </div>
                <hr>
                <div class="input-group">
                    <textarea id="input-comment" class="form-control resize-vert" rows="12" name="comment" placeholder="Escreva aqui"></textarea>
                    <label for="input-comment" id="comment_feedback" class="input-group-addon" data-toggle="tooltip" data-placement="left" title="O comentário deve conter ao menos 10 caracteres">
                        <span class="glyphicon glyphicon-alert icon-color-warning"></span>
                    </label>
                </div>
                <hr>
                <button type="submit" class="btn btn-primary pull-right" onclick="confirm_comment()" disabled>Enviar</button>
            </form>
        </div>
        <br>
        <footer class="page-footer">
            <div class="container">
                Ricardo Maes Zaguini Nunes © 2016
            </div>
        </footer>
        <script src="${resources}/js/jquery.min.js"></script>
        <script src="${resources}/js/bootstrap.min.js"></script>
        <script src="${resources}/js/md5.min.js"></script>
        <script src="${resources}/js/script.js"></script>
        <script>
            $(document).ready(function() {
                $('#btn-contato').addClass('active');
                $('.gravatar').each(function() {
                    var email = $(this).attr('title');
                    if(email != '') {
                        $(this).attr('src', 'http://www.gravatar.com/avatar/' + md5(email));
                    }
                });
            });
        </script>
    </body>
</html>

web/views/header.jsp
<%-- 
    Document   : header
    Created on : May 4, 2016, 9:33:07 PM
    Author     : ricardo
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:if test="${user == null}">
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="${context}/usuario/login">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <label for="input-login-username" class="input-group-addon">Usuário:</label>
                        <input id="input-login-username" type="text" name="username" class="form-control">
                    </div>
                    <div class="input-group">
                        <label for="input-login-password" class="input-group-addon">Senha:</label>
                        <input id="input-login-password" type="password" name="password" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
</c:if>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="nav">
            <ul class="nav navbar-nav navbar-left">
                <li id="btn-home"><a href="#">Home</a></li>
                <li id="btn-projetos"><a href="#">Portfólio</a></li>
                <li id="btn-contato"><a href="#">Depoimentos</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <c:choose>
                <c:when test="${user != null}">
                <li class="dropdown">
                    <button class="dropdown-toggle btn navbar-btn btn-success dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>
                        <span>&nbsp;<c:out value="${user.displayName}"/>&nbsp;</span>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="${context}/usuario/logout" onclick="logout()"><span class="glyphicon glyphicon-log-out text-danger"></span>&nbsp;Sair</a>
                        </li>
                    </ul>
                </li>
                </c:when>
                <c:otherwise>
                <li>
                    <a href="#" data-toggle="modal" data-target="#login-modal">Entrar</a>
                </li>
                </c:otherwise>
                </c:choose>
            </ul>
        </div>
    </div>
</nav>